/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/documents/": {
    get: operations["listDocuments"];
    post: operations["createDocument"];
  };
  "/api/v1/documents/{id}/": {
    get: operations["retrieveDocument"];
    put: operations["updateDocument"];
    delete: operations["destroyDocument"];
    patch: operations["partialUpdateDocument"];
  };
  "/api/v1/users/me/": {
    get: operations["meUserViewSet"];
  };
  "/api/v1/tasks/": {
    get: operations["listTasks"];
    post: operations["createTask"];
  };
  "/api/v1/tasks/{id}/": {
    get: operations["retrieveTask"];
  };
  "/api/v1/users/": {
    post: operations["createUserViewSet"];
  };
  "/api/v1/users/login/": {
    post: operations["loginUserViewSet"];
  };
  "/api/v1/tasks/claim_unassigned_task/": {
    post: operations["claimUnassignedTaskTask"];
  };
  "/api/v1/tasks/{id}/keepalive/": {
    post: operations["keepaliveKeepalive"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Document: {
      /** Format: uuid */
      id?: string;
      name: string;
      /** Format: binary */
      audio_file?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      changed_at?: string;
    };
    Task: {
      /** Format: uuid */
      id?: string;
      document: string;
      /** @enum {string} */
      task_type: "DIARIZE" | "TRANSCRIBE" | "ALIGN";
      progress?: number | null;
      /** @description Task parameters like language, number of speakers, ... */
      task_parameters?: Record<string, never>;
      assigned_worker?: string | null;
      /** Format: date-time */
      last_keepalive?: string;
    };
    Keepalive: {
      progress?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  listDocuments: {
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["Document"])[];
        };
      };
    };
  };
  createDocument: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Document"];
        "application/x-www-form-urlencoded": components["schemas"]["Document"];
        "multipart/form-data": components["schemas"]["Document"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
    };
  };
  retrieveDocument: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
    };
  };
  updateDocument: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Document"];
        "application/x-www-form-urlencoded": components["schemas"]["Document"];
        "multipart/form-data": components["schemas"]["Document"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
    };
  };
  destroyDocument: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      204: never;
    };
  };
  partialUpdateDocument: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Document"];
        "application/x-www-form-urlencoded": components["schemas"]["Document"];
        "multipart/form-data": components["schemas"]["Document"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
    };
  };
  meUserViewSet: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  listTasks: {
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["Task"])[];
        };
      };
    };
  };
  createTask: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Task"];
        "application/x-www-form-urlencoded": components["schemas"]["Task"];
        "multipart/form-data": components["schemas"]["Task"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
    };
  };
  retrieveTask: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
    };
  };
  createUserViewSet: {
    requestBody?: {
      content: {
        "application/json": Record<string, never>;
        "application/x-www-form-urlencoded": Record<string, never>;
        "multipart/form-data": Record<string, never>;
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  loginUserViewSet: {
    requestBody?: {
      content: {
        "application/json": Record<string, never>;
        "application/x-www-form-urlencoded": Record<string, never>;
        "multipart/form-data": Record<string, never>;
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  claimUnassignedTaskTask: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Task"];
        "application/x-www-form-urlencoded": components["schemas"]["Task"];
        "multipart/form-data": components["schemas"]["Task"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
    };
  };
  keepaliveKeepalive: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Keepalive"];
        "application/x-www-form-urlencoded": components["schemas"]["Keepalive"];
        "multipart/form-data": components["schemas"]["Keepalive"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Keepalive"];
        };
      };
    };
  };
}
